### ISSUE TITLE
Error for tasks with parameters

### ISSUE THREAD

**Issue by alexgwasp** [qetza/vsts-psake-task#1]
I tried to input some parameters (like this @{'BuildWorkingFolderNumber'="$(BuildWorkingFolderNumber)"} and this BuildWorkingFolderNumber=14) and it didn't worked. The psake build step doesn't treat parameters in any way that I've tried.

**Comment by qetza** [comment]
Hi @alexbwasp,
The syntax for parameters is a comma- or newline-separated list of name=value. In your example it should be:
BuildWorkingFolderNumber=$(BuildWorkingFolderNumber)

If this is not working, can you run your build with the variable `system.debug` at `true` and send the verbose log (where all task parameters should have been output) of the psake task?

Thanks,

**Comment by alexgwasp** [comment]
Hi @qetza,

I tried again and it did worked! Thanks!
