### ISSUE TITLE
psake step never fails build

### ISSUE THREAD

**Issue by alexgwasp** [qetza/vsts-psake-task#2]
Hi!

The step even with errors never fails the build. Is there a way to fail the build when the psake doesn't do what the task is supposed to that I haven't seen?

**Comment by qetza** [comment]
Hi @alexbwasp,

There's a bug and the build status is not pushed to VSTS. I'll publish a patch for Monday.

Thanks,

**Comment by qetza** [comment]
This is fixed in version 1.1.1 of the extension
